### ISSUE TITLE
[NestJS] Upgrade dependencies to 8.x.x

### ISSUE THREAD

**Issue by Nethanos** [marciopd/json-logger-service#10]
Hi! How have you been? I'm opening this issue cause i tried to open a pull request to your project, upgrading nestJS dependencies to 8.x.x but i was not able to do it due to a 403 HTTP Error. I would like to help you maintain this package cuz it's a very good package and very helpful! Cheers!

## Issue Type:
[X] Upgrade Request

## Motivation
Be according with NestJS latest stable version

**Comment by marciopd** [comment]
@Nethanos does the PR below looks code for you? 

https://github.com/marciopd/json-logger-service/pull/11/files

**Comment by Nethanos** [comment]
Hey @marciopd! how are you? Looks awesome! Thanks!

**Comment by marciopd** [comment]
@Nethanos you're good to go! 

New version 8.0.0 published in NPM: https://www.npmjs.com/package/json-logger-service

**Comment by marciopd** [comment]
If you have an issue or question, please let me know. Take care and see you around!
