### ISSUE TITLE
Pretty print flag

### ISSUE THREAD

**Issue by mits87** [marciopd/json-logger-service#18]
Hi!

First of all, thanks for that service. 
I'm wondering whether it would be possible to implement a pretty print functionality for that service. 
It's very useful for local development. 

Thanks in advance!

**Comment by marciopd** [comment]
@mits87 I just merged and published https://github.com/marciopd/json-logger-service/pull/22 

This part of the docs explains how to use it: https://github.com/marciopd/json-logger-service#pretty-print

Please give it a try and let me know if we can close this one.

Best regards!
